# Generated by Django 3.0.5 on 2023-06-29 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientId', models.PositiveIntegerField(null=True)),
                ('lawyerId', models.PositiveIntegerField(null=True)),
                ('clientName', models.CharField(max_length=40, null=True)),
                ('lawyerName', models.CharField(max_length=40, null=True)),
                ('appointmentDate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDischargeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientId', models.PositiveIntegerField(null=True)),
                ('clientName', models.CharField(max_length=40)),
                ('assignedlawyerName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('case_complaints', models.CharField(max_length=100, null=True)),
                ('complaintDate', models.DateField()),
                ('releaseDate', models.DateField()),
                ('daySpent', models.PositiveIntegerField()),
                ('hoursCharge', models.PositiveIntegerField()),
                ('resourceCost', models.PositiveIntegerField()),
                ('lawyerFee', models.PositiveIntegerField()),
                ('OtherCharge', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/LawyerProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(choices=[('Bankruptcy Lawyer', 'Bankruptcy Lawyer'), ('Business Lawyer (Corporate Lawyer)', 'Business Lawyer (Corporate Lawyer)'), ('Constitutional Lawyer', 'Constitutional Lawyer'), ('Criminal Defense Lawyer', 'Criminal Defense Lawyer'), ('Employment and Labor Lawyer', 'Employment and Labor Lawyer'), ('Entertainment Lawyer', 'Entertainment Lawyer'), ('Estate Planning Lawyer', 'Estate Planning Lawyer'), ('Family Lawyer', 'Family Lawyer'), ('Immigration Lawyer', 'Immigration Lawyer'), ('Intellectual Property (IP) Lawyer', 'Intellectual Property (IP) Lawyer'), ('Personal Injury Lawyer', 'Personal Injury Lawyer'), ('Tax Lawyer', 'Tax Lawyer')], default='Criminal Defense Lawyer', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/ClientProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('case_complaint', models.CharField(max_length=100)),
                ('assignedLawyerId', models.PositiveIntegerField(null=True)),
                ('complaintDate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
